version: "3.9"
services:
  api:
    container_name: "${APP_NAME}-nodejs"
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:debug
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - mysql
    restart: on-failure
  mysql:
    container_name: "${APP_NAME}-mysql"
    image: mysql:5.7
    volumes:
      - storage_db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - default
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    restart: on-failure  
networks:
  default:
    driver: bridge
volumes:
  storage_api:
  storage_db:
